import { HotspotEvent, ThermalClassification, Facility } from "./types";

const now = new Date().toISOString();

export const mockEvents: HotspotEvent[] = [
  // ── 1. Jamnagar Petrochemical Complex (Gujarat) ─────────────────────────
  {
    id: "evt-001",
    latitude: 22.368,
    longitude: 69.832,
    h3_index: "88619a6953fffff",
    brightness_temp_kelvin: 942.5,
    frp_megawatts: 842.0,
    confidence_pct: 98,
    satellite_source: "VIIRS_SNPP_NRT",
    day_night: "N",
    acq_datetime: now,
    classification: ThermalClassification.INDUSTRIAL_FIRE_EMERGENCY,
    confidence_score: 0.96,
    cde_anomaly_score: 5.8,
    facility_name: "Reliance Jamnagar Petrochemical Complex",
    facility_type: "refinery",
    distance_to_facility_km: 0.12,
    is_critical_alert: true,
    agent_reasoning: {
      spatial_agent: "ST_Contains=TRUE (within industrial polygon)",
      temporal_agent: "FRP +5.8σ above 30-day baseline (μ=142 MW)",
      vision_agent: "Sentinel-2 SWIR confirms flame expansion past flare stack tip",
      cde_verdict: "THERMODYNAMIC_CATASTROPHIC_RUNAWAY",
    },
    created_at: now,
  },
  {
    id: "evt-001b",
    latitude: 22.371,
    longitude: 69.835,
    h3_index: "88619a6953fffff",
    brightness_temp_kelvin: 765.0,
    frp_megawatts: 180.0,
    confidence_pct: 94,
    satellite_source: "VIIRS_SNPP_NRT",
    day_night: "N",
    acq_datetime: now,
    classification: ThermalClassification.PERSISTENT_INDUSTRIAL_FLARE,
    confidence_score: 0.93,
    cde_anomaly_score: 0.8,
    facility_name: "Reliance Jamnagar Flare Stack #4",
    facility_type: "refinery",
    distance_to_facility_km: 0.25,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "Co-located with flare stack footprint",
      temporal_agent: "Matches 30-day baseline",
      cde_verdict: "PERSISTENT_INDUSTRIAL_FLARE",
    },
    created_at: now,
  },

  // ── 2. BPCL Kochi Refinery (Kerala) ──────────────────────────────────────
  {
    id: "evt-006",
    latitude: 9.992,
    longitude: 76.358,
    h3_index: "8860a12563fffff",
    brightness_temp_kelvin: 885.0,
    frp_megawatts: 420.0,
    confidence_pct: 95,
    satellite_source: "VIIRS_NOAA20_NRT",
    day_night: "N",
    acq_datetime: now,
    classification: ThermalClassification.INDUSTRIAL_FIRE_EMERGENCY,
    confidence_score: 0.94,
    cde_anomaly_score: 4.2,
    facility_name: "BPCL Kochi Refinery (Ambalamugal)",
    facility_type: "refinery",
    distance_to_facility_km: 0.08,
    is_critical_alert: true,
    agent_reasoning: {
      spatial_agent: "Contained in BPCL Kochi industrial polygon",
      temporal_agent: "FRP surge +4.2σ above baseline",
      vision_agent: "SWIR thermal anomaly outside flare bounds",
      cde_verdict: "THERMODYNAMIC_CATASTROPHIC_RUNAWAY",
    },
    created_at: now,
  },
  {
    id: "evt-006b",
    latitude: 9.994,
    longitude: 76.361,
    h3_index: "8860a12563fffff",
    brightness_temp_kelvin: 690.0,
    frp_megawatts: 95.0,
    confidence_pct: 91,
    satellite_source: "VIIRS_NOAA20_NRT",
    day_night: "N",
    acq_datetime: now,
    classification: ThermalClassification.PERSISTENT_INDUSTRIAL_FLARE,
    confidence_score: 0.91,
    cde_anomaly_score: 0.4,
    facility_name: "BPCL Kochi Catalytic Cracker Unit",
    facility_type: "refinery",
    distance_to_facility_km: 0.15,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "Co-located with CCU flare stack",
      temporal_agent: "Normal diurnal thermal profile",
      cde_verdict: "PERSISTENT_INDUSTRIAL_FLARE",
    },
    created_at: now,
  },

  // ── 3. CPCL Chennai Manali Refinery (Tamil Nadu) ─────────────────────────
  {
    id: "evt-007",
    latitude: 13.168,
    longitude: 80.257,
    h3_index: "8861892543fffff",
    brightness_temp_kelvin: 780.0,
    frp_megawatts: 210.0,
    confidence_pct: 93,
    satellite_source: "VIIRS_SNPP_NRT",
    day_night: "N",
    acq_datetime: now,
    classification: ThermalClassification.PERSISTENT_INDUSTRIAL_FLARE,
    confidence_score: 0.92,
    cde_anomaly_score: 1.1,
    facility_name: "CPCL Manali Refinery Chennai",
    facility_type: "refinery",
    distance_to_facility_km: 0.18,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "Inside CPCL Manali complex boundaries",
      temporal_agent: "Within 2σ 60-day baseline envelope",
      cde_verdict: "PERSISTENT_INDUSTRIAL_FLARE",
    },
    created_at: now,
  },

  // ── 4. IOCL Haldia Refinery (West Bengal) ────────────────────────────────
  {
    id: "evt-002",
    latitude: 22.031,
    longitude: 88.082,
    h3_index: "88619a0815fffff",
    brightness_temp_kelvin: 780.0,
    frp_megawatts: 145.0,
    confidence_pct: 96,
    satellite_source: "VIIRS_SNPP_NRT",
    day_night: "N",
    acq_datetime: now,
    classification: ThermalClassification.PERSISTENT_INDUSTRIAL_FLARE,
    confidence_score: 0.94,
    cde_anomaly_score: 0.6,
    facility_name: "IOCL Haldia Refinery Flare Stack",
    facility_type: "refinery",
    distance_to_facility_km: 0.08,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "ST_Contains=TRUE (IOCL Haldia refinery polygon)",
      temporal_agent: "Matches 30-day baseline (μ=138 MW, σ=16 MW)",
      vision_agent: "SWIR thermal emission confined to 20m flare tip",
      cde_verdict: "NORMAL_CONTINUOUS_OPERATION",
    },
    created_at: now,
  },

  // ── 5. BPCL Mumbai Refinery (Maharashtra) ────────────────────────────────
  {
    id: "evt-011",
    latitude: 19.014,
    longitude: 72.894,
    h3_index: "88609a6523fffff",
    brightness_temp_kelvin: 810.0,
    frp_megawatts: 165.0,
    confidence_pct: 94,
    satellite_source: "VIIRS_SNPP_NRT",
    day_night: "N",
    acq_datetime: now,
    classification: ThermalClassification.PERSISTENT_INDUSTRIAL_FLARE,
    confidence_score: 0.93,
    cde_anomaly_score: 0.7,
    facility_name: "BPCL Mumbai Mahul Refinery",
    facility_type: "refinery",
    distance_to_facility_km: 0.12,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "Within Mahul industrial perimeter",
      temporal_agent: "Baseline matched (μ=155 MW)",
      cde_verdict: "PERSISTENT_INDUSTRIAL_FLARE",
    },
    created_at: now,
  },

  // ── 6. HPCL Visakh Refinery (Andhra Pradesh) ─────────────────────────────
  {
    id: "evt-008",
    latitude: 17.724,
    longitude: 83.265,
    h3_index: "88619a2853fffff",
    brightness_temp_kelvin: 795.0,
    frp_megawatts: 155.0,
    confidence_pct: 92,
    satellite_source: "VIIRS_NOAA20_NRT",
    day_night: "N",
    acq_datetime: now,
    classification: ThermalClassification.PERSISTENT_INDUSTRIAL_FLARE,
    confidence_score: 0.91,
    cde_anomaly_score: 0.5,
    facility_name: "HPCL Visakh Refinery Flare Unit",
    facility_type: "refinery",
    distance_to_facility_km: 0.14,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "Inside HPCL Visakhapatnam polygon",
      temporal_agent: "Diurnal pattern verified",
      cde_verdict: "PERSISTENT_INDUSTRIAL_FLARE",
    },
    created_at: now,
  },

  // ── 7. Punjab Agricultural Stubble Burning Belt ──────────────────────────
  {
    id: "evt-003",
    latitude: 30.901,
    longitude: 75.857,
    h3_index: "88619a0a4bfffff",
    brightness_temp_kelvin: 368.0,
    frp_megawatts: 42.0,
    confidence_pct: 88,
    satellite_source: "VIIRS_NOAA20_NRT",
    day_night: "D",
    acq_datetime: now,
    classification: ThermalClassification.AGRICULTURAL_BURNING,
    confidence_score: 0.89,
    cde_anomaly_score: 0.1,
    facility_name: "Ludhiana District Paddy Fields",
    facility_type: "farmland",
    distance_to_facility_km: 24.5,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "WorldCover class=40 (Cropland)",
      temporal_agent: "Seasonal post-harvest surge (October-November peak)",
      cde_verdict: "AGRICULTURAL_CROP_RESIDUE_BURNING",
    },
    created_at: now,
  },
  {
    id: "evt-003b",
    latitude: 30.245,
    longitude: 75.842,
    h3_index: "88619a0a4bfffff",
    brightness_temp_kelvin: 372.0,
    frp_megawatts: 48.0,
    confidence_pct: 91,
    satellite_source: "VIIRS_SNPP_NRT",
    day_night: "D",
    acq_datetime: now,
    classification: ThermalClassification.AGRICULTURAL_BURNING,
    confidence_score: 0.92,
    cde_anomaly_score: 0.1,
    facility_name: "Sangrur Farm Cluster #12",
    facility_type: "farmland",
    distance_to_facility_km: 18.2,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "WorldCover class=40 (Cropland)",
      temporal_agent: "Active stubble burning footprint",
      cde_verdict: "AGRICULTURAL_BURNING",
    },
    created_at: now,
  },
  {
    id: "evt-003c",
    latitude: 30.211,
    longitude: 74.945,
    h3_index: "88619a0a4bfffff",
    brightness_temp_kelvin: 375.0,
    frp_megawatts: 52.0,
    confidence_pct: 90,
    satellite_source: "VIIRS_SNPP_NRT",
    day_night: "D",
    acq_datetime: now,
    classification: ThermalClassification.AGRICULTURAL_BURNING,
    confidence_score: 0.90,
    cde_anomaly_score: 0.1,
    facility_name: "Bathinda Paddy Fields Sector 4",
    facility_type: "farmland",
    distance_to_facility_km: 22.0,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "Agricultural zoning confirmed",
      temporal_agent: "Daytime thermal spike",
      cde_verdict: "AGRICULTURAL_BURNING",
    },
    created_at: now,
  },
  {
    id: "evt-003d",
    latitude: 31.634,
    longitude: 74.872,
    h3_index: "88619a0a4bfffff",
    brightness_temp_kelvin: 365.0,
    frp_megawatts: 38.0,
    confidence_pct: 87,
    satellite_source: "VIIRS_NOAA20_NRT",
    day_night: "D",
    acq_datetime: now,
    classification: ThermalClassification.AGRICULTURAL_BURNING,
    confidence_score: 0.88,
    cde_anomaly_score: 0.1,
    facility_name: "Amritsar Rural Agriculture Zone",
    facility_type: "farmland",
    distance_to_facility_km: 16.5,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "Cropland land cover verified",
      temporal_agent: "Transient daytime anomaly",
      cde_verdict: "AGRICULTURAL_BURNING",
    },
    created_at: now,
  },

  // ── 8. Haryana Crop Burning Belt ─────────────────────────────────────────
  {
    id: "evt-005a",
    latitude: 29.685,
    longitude: 76.990,
    h3_index: "88619a0523fffff",
    brightness_temp_kelvin: 362.0,
    frp_megawatts: 36.0,
    confidence_pct: 89,
    satellite_source: "VIIRS_SNPP_NRT",
    day_night: "D",
    acq_datetime: now,
    classification: ThermalClassification.AGRICULTURAL_BURNING,
    confidence_score: 0.89,
    cde_anomaly_score: 0.1,
    facility_name: "Karnal Paddy Fields",
    facility_type: "farmland",
    distance_to_facility_km: 19.8,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "WorldCover class=40 (Cropland)",
      temporal_agent: "Post-harvest burning period",
      cde_verdict: "AGRICULTURAL_BURNING",
    },
    created_at: now,
  },
  {
    id: "evt-005b",
    latitude: 29.801,
    longitude: 76.399,
    h3_index: "88619a0523fffff",
    brightness_temp_kelvin: 365.0,
    frp_megawatts: 39.0,
    confidence_pct: 88,
    satellite_source: "VIIRS_NOAA20_NRT",
    day_night: "D",
    acq_datetime: now,
    classification: ThermalClassification.AGRICULTURAL_BURNING,
    confidence_score: 0.88,
    cde_anomaly_score: 0.1,
    facility_name: "Kaithal Crop Fields",
    facility_type: "farmland",
    distance_to_facility_km: 21.0,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "Open farm fields",
      temporal_agent: "Daytime agricultural fire",
      cde_verdict: "AGRICULTURAL_BURNING",
    },
    created_at: now,
  },

  // ── 9. Western UP Crop Burning ───────────────────────────────────────────
  {
    id: "evt-009a",
    latitude: 28.984,
    longitude: 77.706,
    h3_index: "88619a0613fffff",
    brightness_temp_kelvin: 358.0,
    frp_megawatts: 32.0,
    confidence_pct: 86,
    satellite_source: "VIIRS_SNPP_NRT",
    day_night: "D",
    acq_datetime: now,
    classification: ThermalClassification.AGRICULTURAL_BURNING,
    confidence_score: 0.87,
    cde_anomaly_score: 0.1,
    facility_name: "Meerut Sugarcane Farm Cluster",
    facility_type: "farmland",
    distance_to_facility_km: 28.4,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "Cropland land cover verified",
      temporal_agent: "Sugarcane residue burning",
      cde_verdict: "AGRICULTURAL_BURNING",
    },
    created_at: now,
  },

  // ── 10. Maharashtra Crop Residue (Vidarbha) ──────────────────────────────
  {
    id: "evt-010a",
    latitude: 20.389,
    longitude: 78.130,
    h3_index: "88619a0715fffff",
    brightness_temp_kelvin: 355.0,
    frp_megawatts: 28.0,
    confidence_pct: 85,
    satellite_source: "VIIRS_NOAA20_NRT",
    day_night: "D",
    acq_datetime: now,
    classification: ThermalClassification.AGRICULTURAL_BURNING,
    confidence_score: 0.86,
    cde_anomaly_score: 0.1,
    facility_name: "Yavatmal Cotton Residue Burning",
    facility_type: "farmland",
    distance_to_facility_km: 35.0,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "Cropland land cover verified",
      temporal_agent: "Post-harvest cotton stalks burning",
      cde_verdict: "AGRICULTURAL_BURNING",
    },
    created_at: now,
  },

  // ── 11. Forest Wildfires (Himalayan / Odisha Forests) ─────────────────────
  {
    id: "evt-004",
    latitude: 30.082,
    longitude: 78.241,
    h3_index: "88619a0463fffff",
    brightness_temp_kelvin: 415.0,
    frp_megawatts: 75.0,
    confidence_pct: 92,
    satellite_source: "VIIRS_NOAA20_NRT",
    day_night: "D",
    acq_datetime: now,
    classification: ThermalClassification.WILDFIRE,
    confidence_score: 0.91,
    cde_anomaly_score: 0.2,
    facility_name: "Rajaji National Park Buffer",
    facility_type: "forest_reserve",
    distance_to_facility_km: 48.0,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "WorldCover class=10 (Tree cover / Deciduous Forest)",
      temporal_agent: "Linear spreading thermal front across 3km",
      vision_agent: "Sentinel-2 NIR false-color shows active burn perimeter",
      cde_verdict: "ACTIVE_FOREST_WILDFIRE",
    },
    created_at: now,
  },
  {
    id: "evt-004b",
    latitude: 21.650,
    longitude: 86.350,
    h3_index: "88619a0463fffff",
    brightness_temp_kelvin: 430.0,
    frp_megawatts: 85.0,
    confidence_pct: 94,
    satellite_source: "VIIRS_SNPP_NRT",
    day_night: "D",
    acq_datetime: now,
    classification: ThermalClassification.WILDFIRE,
    confidence_score: 0.93,
    cde_anomaly_score: 0.2,
    facility_name: "Simlipal Biosphere Reserve",
    facility_type: "forest_reserve",
    distance_to_facility_km: 52.0,
    is_critical_alert: false,
    agent_reasoning: {
      spatial_agent: "Dense forest cover (class 10)",
      temporal_agent: "Spreading wildfire front",
      cde_verdict: "WILDFIRE",
    },
    created_at: now,
  },
];

export const mockFacilities: Facility[] = [
  {
    id: "fac-001",
    osm_id: "node/101",
    name: "Reliance Jamnagar Petrochemical Complex",
    facility_type: "refinery",
    latitude: 22.368,
    longitude: 69.832,
    operator: "Reliance Industries Ltd",
    state: "Gujarat",
    district: "Jamnagar",
    baseline_frp_mean: 142.0,
    baseline_frp_std: 18.5,
    active_hotspots_count: 2,
  },
  {
    id: "fac-002",
    osm_id: "node/102",
    name: "IOCL Haldia Refinery",
    facility_type: "refinery",
    latitude: 22.031,
    longitude: 88.082,
    operator: "Indian Oil Corporation Ltd",
    state: "West Bengal",
    district: "Purba Medinipur",
    baseline_frp_mean: 138.0,
    baseline_frp_std: 16.2,
    active_hotspots_count: 1,
  },
  {
    id: "fac-003",
    osm_id: "node/103",
    name: "Tata Steel Jamshedpur Works",
    facility_type: "metal_works",
    latitude: 22.804,
    longitude: 86.202,
    operator: "Tata Steel Ltd",
    state: "Jharkhand",
    district: "East Singhbhum",
    baseline_frp_mean: 195.0,
    baseline_frp_std: 22.0,
    active_hotspots_count: 0,
  },
  {
    id: "fac-004",
    osm_id: "node/104",
    name: "IOCL Panipat Refinery",
    facility_type: "refinery",
    latitude: 29.390,
    longitude: 76.963,
    operator: "Indian Oil Corporation Ltd",
    state: "Haryana",
    district: "Panipat",
    baseline_frp_mean: 135.0,
    baseline_frp_std: 15.0,
    active_hotspots_count: 0,
  },
  {
    id: "fac-005",
    osm_id: "node/105",
    name: "BPCL Mumbai Refinery (Mahul)",
    facility_type: "refinery",
    latitude: 19.014,
    longitude: 72.894,
    operator: "Bharat Petroleum Corporation Ltd",
    state: "Maharashtra",
    district: "Mumbai Suburban",
    baseline_frp_mean: 155.0,
    baseline_frp_std: 17.0,
    active_hotspots_count: 1,
  },
  {
    id: "fac-006",
    osm_id: "node/106",
    name: "BPCL Kochi Refinery (Ambalamugal)",
    facility_type: "refinery",
    latitude: 9.992,
    longitude: 76.358,
    operator: "Bharat Petroleum Corporation Ltd",
    state: "Kerala",
    district: "Ernakulam",
    baseline_frp_mean: 140.0,
    baseline_frp_std: 16.5,
    active_hotspots_count: 2,
  },
  {
    id: "fac-007",
    osm_id: "node/107",
    name: "CPCL Manali Refinery Chennai",
    facility_type: "refinery",
    latitude: 13.168,
    longitude: 80.257,
    operator: "Chennai Petroleum Corp Ltd",
    state: "Tamil Nadu",
    district: "Chennai",
    baseline_frp_mean: 148.0,
    baseline_frp_std: 17.5,
    active_hotspots_count: 1,
  },
  {
    id: "fac-008",
    osm_id: "node/108",
    name: "HPCL Visakh Refinery",
    facility_type: "refinery",
    latitude: 17.724,
    longitude: 83.265,
    operator: "Hindustan Petroleum Corporation Ltd",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    baseline_frp_mean: 150.0,
    baseline_frp_std: 16.0,
    active_hotspots_count: 1,
  },
];
